FROM nvcr.io/nvidia/pytorch:25.12-py3


RUN apt update && apt install -y ssh
RUN echo "root:123456"|chpasswd
RUN mkdir -vp /run/sshd
RUN sed -i '$a PermitRootLogin yes' /etc/ssh/sshd_config
RUN export -p >/root/env_var.sh
RUN sed -i '$a source /root/env_var.sh' /root/.bashrc
ENTRYPOINT ["/usr/sbin/sshd","-D"]