FROM nvcr.io/nvidia/pytorch:25.12-py3


RUN apt update && apt install -y ssh tmux
RUN echo "root:123456"|chpasswd
RUN mkdir -vp /run/sshd
RUN sed -i '$a PermitRootLogin yes' /etc/ssh/sshd_config
RUN export -p >/root/env_var.sh
RUN echo 'export https_proxy=http://127.0.0.1:7897' >> /root/.bashrc && \
    echo 'export all_proxy=http://127.0.0.1:7897' >> /root/.bashrc && \
    echo "export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_ed25519_wiketool'" >> /root/.bashrc
RUN sed -i '$a source /root/env_var.sh' /root/.bashrc
ENTRYPOINT ["/usr/sbin/sshd","-D"]
